CC = g++
CPPFLAGS = -maccumulate-outgoing-args -w -O3 -c -D_INTEL -D_LINUX -D_LINUX64 -D_NO_EXCEPT -I../../Libraries/XMLFoundation/inc -I../../Libraries/Xfer/inc
COPY = cp

TransactXML: \
	clear \
	Console.o 
	 
	$(CC) \
		-o 5Loaves \
		-L../../Libraries/XMLFoundation/Build \
		-L../../Libraries/openssl/bin-linux64 \
		Console.o \
		-lpthread -lnsl -ldl -lXMLFoundation -lssl -lcrypto

SocketServer.o: ./Console.cpp
	$(CC) $(CPPFLAGS) ./Console.cpp -o ./Console.o


clear:
	clear

